location:
  source_directories:
  - /home/croissong
  repositories:
  - /tmp/local.borg

  exclude_patterns:
    - '*.pyc'
    - '*/node_modules/'
    - '*/tmp/'
    - '*/scratch/'

  exclude_caches: true
  exclude_if_present:
    - .nobackup

retention:
    # Retention policy for how many backups to keep.
    keep_daily: 7
    keep_weekly: 4
    keep_monthly: 6
