[[snippets]]
  description = "jq yq alternative"
  command = "dasel"
  tag = ["jq", "yq"]
  output = ""

[[snippets]]
  description = "jwt certificates"
  command = "step-cli"
  tag = ["jwt", "certificates", "ssl"]
  output = ""

[[snippets]]
  description = "golint alternative"
  command = "revive"
  tag = ["golang", "lint"]
  output = ""

[[snippets]]
  description = "wbench mitmproxy 8118"
  command = "mitmdump -p 8118 --set client_certs=/home/croissong/.config/ssl/client-certs/ -q"
  output = ""
