[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#697700"

[icons]
name = "none"
[icons.overrides]
cogs = ""
bat_full = " 100%"
bat_charging = " + "
bat_discharging = " - "
thermometer = " C° "


[[block]]
block = "custom"
command = "$XDG_CONFIG_HOME/i3status-rust/pomodoro-block.sh"
json = true
interval = 30

[[block]]
block = "load"
interval = 60
format = "{1m}"

[[block]]
block = "temperature"
interval = 60
chip = "coretemp-isa-*"
format = "{min} min, {max} max, {average} avg"

[[block]]
block = "battery"
interval = 60
driver = "upower"
device = "DisplayDevice"
format = "{percentage}%"

[[block]]
block = "time"
interval = 60
format = "%A %m-%d %H:%M"
